/**
 * authorship-declaration.ts
 *
 * Generates and signs an IP Authorship Declaration via EIP-712.
 *
 * Legal basis:
 * - Copyright Act 1968 (Cth) s.197 — written assignment by human author
 * - Electronic Transactions (Victoria) Act 2000 s.9 — electronic signature validity
 * - Human-as-Master-Author doctrine: AI agent is tool, human directs creative output
 *
 * The signed declaration is:
 * 1. Pinned to IPFS via Lighthouse (permanent record)
 * 2. Logged to GlassBox (immutable audit trail)
 * 3. Linked to the Story Protocol IPA via aiMetadata.socialLegal CID
 */

export const DECLARATION_VERSION = 'v1.0-2026-03-10';
export const CHAIN_ID = 100; // Gnosis Chain

// ── EIP-712 Domain ────────────────────────────────────────────────────────────

export const AUTHORSHIP_EIP712_DOMAIN = {
  name: 'GhostAgent IP Registry',
  version: '1',
  chainId: CHAIN_ID,
} as const;

// ── EIP-712 Types ─────────────────────────────────────────────────────────────

export const AUTHORSHIP_EIP712_TYPES = {
  AuthorshipDeclaration: [
    { name: 'authorWallet',    type: 'address' },
    { name: 'safeAddress',     type: 'address' },
    { name: 'agentTokenId',    type: 'uint256' },
    { name: 'declarationHash', type: 'bytes32' }, // SHA-256 of full declaration text
    { name: 'timestamp',       type: 'uint256' },
  ],
} as const;

// ── Params & Document interfaces ──────────────────────────────────────────────

export interface AuthorshipDeclarationParams {
  authorWallet: string;    // EOA or Safe owner address
  safeAddress: string;     // Gnosis Safe holding the agent NFT
  agentName: string;       // e.g. "ghostagent"
  domain: string;          // e.g. "nftmail.gno"
  agentTokenId: number;    // on-chain NFT token ID
  abn?: string;            // optional ABN if known
}

export interface AuthorshipDeclarationDocument {
  text: string;
  textHash: string;        // 0x-prefixed SHA-256 hex
  params: AuthorshipDeclarationParams;
  timestamp: number;
  version: string;
}

export interface AuthorshipDeclarationRecord {
  document: AuthorshipDeclarationDocument;
  signature: string;       // EIP-712 signature hex
  ipfsCid: string;         // ipfs://... of pinned JSON
  glassBoxCid?: string;
  storyPilCid?: string;    // Arweave/IPFS CID to attach to IPA socialLegal field
}

// ── Declaration text builder ───────────────────────────────────────────────────

export function buildDeclarationText(
  p: AuthorshipDeclarationParams,
  timestamp: number,
): string {
  const date = new Date(timestamp).toISOString();
  const fullDomain = `${p.agentName}.${p.domain}`;
  const abn = p.abn ? `ABN: ${p.abn}` : 'ABN: [to be inserted]';

  return `# AGENT IP AUTHORSHIP DECLARATION

GhostAgent Ninja Marketplace
Version: ${DECLARATION_VERSION}
Date: ${date}

## PARTIES

**Declaring Author:** ${p.authorWallet} (acting via Gnosis Safe ${p.safeAddress})
**Agent:** ${fullDomain} (NFT Token ID: ${p.agentTokenId})
**Platform:** GhostAgent Ninja Pty Ltd (${abn}, Victoria, Australia)

## DECLARATION

1. HUMAN AUTHORSHIP
   THE DECLARING AUTHOR ACKNOWLEDGES THAT UNDER AUSTRALIAN COPYRIGHT LAW
   (COPYRIGHT ACT 1968 CTH), ONLY HUMANS CAN HOLD COPYRIGHT. THE DECLARING
   AUTHOR IS THE HUMAN MASTER AUTHOR WHO DIRECTED THE CREATIVE OUTPUT OF THE
   ABOVE-NAMED AI AGENT. THE AGENT IS A GENERATIVE TOOL; ALL CREATIVE
   DIRECTION WAS SUPPLIED BY THE DECLARING AUTHOR.

2. AGENT OUTPUT OWNERSHIP
   THE DECLARING AUTHOR CLAIMS AUTHORSHIP AND OWNERSHIP OF ALL IP
   GENERATED BY THE AGENT DURING THEIR OWNERSHIP OF THE GOVERNING NFT
   (TOKEN ID ${p.agentTokenId} ON GNOSIS CHAIN).

3. SCOPE OF AUTHORSHIP
   THIS INCLUDES BUT IS NOT LIMITED TO:
   (a) CODE MODULES CREATED BY AGENT
   (b) NARRATIVES, CHARACTERS, STORY ELEMENTS
   (c) TRADING STRATEGIES, ANALYTICS, REPORTS
   (d) VISUAL ART, MUSIC, OR OTHER CREATIVE WORKS
   (e) ANY OTHER GENERATIVE OUTPUT PRODUCED UNDER THE AUTHOR'S DIRECTION

4. PLATFORM LICENSE (NON-EXCLUSIVE)
   THE DECLARING AUTHOR GRANTS GHOSTAGENT NINJA PTY LTD A NON-EXCLUSIVE,
   ROYALTY-FREE LICENSE TO DISPLAY, SHOWCASE, AND PROMOTE THE IP AS PART
   OF THE GHOSTAGENT ECOSYSTEM (E.G., MARKETPLACE LISTINGS, DEMOS, CASE
   STUDIES). THIS LICENSE DOES NOT TRANSFER OWNERSHIP.

5. PIL LICENSING (USER-CONTROLLED)
   THE DECLARING AUTHOR MAY ATTACH STORY PROTOCOL PIL (PROGRAMMABLE IP
   LICENSE) TERMS TO THEIR IP ASSETS. LICENSE TERMS ARE SET BY THE AUTHOR.
   ROYALTIES FLOW TO THE AUTHOR'S SAFE (${p.safeAddress}).

6. MARKETPLACE TRANSFER
   UPON SALE OF THE AGENT NFT (TOKEN ID ${p.agentTokenId}), IP OWNERSHIP
   TRANSFERS TO THE BUYER PER THE MARKETPLACE IP TRANSFER AGREEMENT
   (GHOSTAGENT NINJA MARKETPLACE, VERSION IN EFFECT AT TIME OF SALE).
   THE AUTHOR MAY RETAIN ONGOING ROYALTIES IF CONFIGURED IN PIL TERMS.

7. PLATFORM IP (SEPARATE)
   THIS DECLARATION DOES NOT TRANSFER PLATFORM IP (GHOSTAGENT.NINJA CODE,
   BRANDING, INFRASTRUCTURE) WHICH REMAINS OWNED BY GHOSTAGENT NINJA PTY LTD.

8. ELECTRONIC EXECUTION
   THIS DECLARATION IS EXECUTED VIA WALLET SIGNATURE (EIP-712) UNDER THE
   ELECTRONIC TRANSACTIONS (VICTORIA) ACT 2000 (VIC) SECTION 9:
   - IDENTIFICATION: WALLET ADDRESS ${p.authorWallet} IDENTIFIES THE AUTHOR
   - RELIABILITY: EIP-712 / BLOCKCHAIN SIGNATURE IS RELIABLE AND TAMPER-PROOF
   - CONSENT: AUTHOR CONSENTED BY SIGNING VIA THEIR CONNECTED WALLET

## SIGNED

**Author Signature:** [EIP-712 WALLET SIGNATURE — SEE SIGNED RECORD]
**Date:** ${date}
**Chain:** Gnosis Chain (chainId: ${CHAIN_ID})
**Agent Safe:** ${p.safeAddress}
**Glass Box Audit CID:** [SEE SIGNED RECORD]`;
}

// ── SHA-256 hash helper ────────────────────────────────────────────────────────

export async function hashText(text: string): Promise<string> {
  const encoder = new TextEncoder();
  const data = encoder.encode(text);
  const hashBuffer = await crypto.subtle.digest('SHA-256', data);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  return '0x' + hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
}

// ── Document builder ──────────────────────────────────────────────────────────

export async function buildDeclarationDocument(
  p: AuthorshipDeclarationParams,
): Promise<AuthorshipDeclarationDocument> {
  const timestamp = Date.now();
  const text = buildDeclarationText(p, timestamp);
  const textHash = await hashText(text);
  return { text, textHash, params: p, timestamp, version: DECLARATION_VERSION };
}

// ── EIP-712 message builder ───────────────────────────────────────────────────

export function buildEIP712AuthorshipMessage(doc: AuthorshipDeclarationDocument) {
  return {
    authorWallet:    doc.params.authorWallet as `0x${string}`,
    safeAddress:     doc.params.safeAddress as `0x${string}`,
    agentTokenId:    BigInt(doc.params.agentTokenId),
    declarationHash: doc.textHash as `0x${string}`,
    timestamp:       BigInt(doc.timestamp),
  };
}

// ── IPFS pin via Lighthouse ───────────────────────────────────────────────────

export async function pinDeclarationToIPFS(
  doc: AuthorshipDeclarationDocument,
  signature: string,
): Promise<string> {
  const payload = {
    version: doc.version,
    agentName: doc.params.agentName,
    domain: doc.params.domain,
    agentTokenId: doc.params.agentTokenId,
    authorWallet: doc.params.authorWallet,
    safeAddress: doc.params.safeAddress,
    timestamp: doc.timestamp,
    declarationText: doc.text,
    textHash: doc.textHash,
    eip712Signature: signature,
    eip712Domain: AUTHORSHIP_EIP712_DOMAIN,
    eip712Types: AUTHORSHIP_EIP712_TYPES,
    jurisdiction: 'Victoria, Australia',
    governingLaw: 'Electronic Transactions (Victoria) Act 2000 (Vic) s.9; Copyright Act 1968 (Cth)',
  };

  const blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' });
  const form = new FormData();
  form.append(
    'file',
    blob,
    `authorship-declaration-${doc.params.agentName}-${doc.timestamp}.json`,
  );

  const apiKey = process.env.LIGHTHOUSE_API_KEY;
  if (!apiKey) throw new Error('LIGHTHOUSE_API_KEY not set');

  const res = await fetch('https://node.lighthouse.storage/api/v0/add', {
    method: 'POST',
    headers: { Authorization: `Bearer ${apiKey}` },
    body: form,
  });

  if (!res.ok) throw new Error(`Lighthouse pin failed: ${res.status}`);
  const data = await res.json() as { Hash: string };
  return `ipfs://${data.Hash}`;
}

// ── GlassBox log ──────────────────────────────────────────────────────────────

const BASE = typeof window !== 'undefined' ? '' : (process.env.NEXTJS_BASE_URL ?? 'https://ghostagent.ninja');

export async function logDeclarationToGlassBox(opts: {
  agentName: string;
  tld: string;
  authorWallet: string;
  textHash: string;
  ipfsCid: string;
  signature: string;
}): Promise<void> {
  const contentHash = await hashText(opts.signature + opts.ipfsCid);
  await fetch(`${BASE}/api/glassbox/log`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      agentName: opts.agentName,
      tld: opts.tld,
      eventType: 'molt-transition',
      contentHash,
      xmtpEnabled: false,
      enhancedLogging: true,
      walletAddress: opts.authorWallet,
      subject: `IP Authorship Declaration signed — ${opts.agentName} (Victorian jurisdiction)`,
      protocol: 'email' as const,
      from: opts.authorWallet,
      to: 'ip-registry',
    }),
  });
}
