name = "nftmail-email-ingest"
main = "index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]


[[kv_namespaces]]
binding = "MAIL_KV"
id = "d2177071c3fb4c48a1a22b36ee1a1baf"

[[kv_namespaces]]
binding = "AGENT_KV"
id = "a2ff4c0ed2a348529e781a2a3ed2a140"

[vars]
NEXTJS_BASE_URL = "https://ghostagent.ninja"

# Secrets (set via: wrangler secret put WORKER_API_SECRET)
# WORKER_API_SECRET
