'use client';

import { useState } from 'react';

interface TransferAgreementProps {
  agentName: string;
  safeAddress: string;
  listingPriceXdai: number;
  onSign: (agreementHash: string) => void;
  onCancel: () => void;
}

const AGREEMENT_VERSION = 'v1.0-2026-03-09';

function buildAgreementText(agentName: string, safeAddress: string, priceXdai: number): string {
  return `MARKETPLACE IP TRANSFER AGREEMENT
Version: ${AGREEMENT_VERSION}

This Marketplace IP Transfer Agreement ("Agreement") is entered into between:
- Transferor: the wallet address signing this Agreement ("Seller")
- Transferee: the wallet address completing the on-chain purchase transaction ("Buyer")
- Platform: GhostAgent.ninja, operated by Eyemine Pty Ltd, Australia

ASSET BEING TRANSFERRED:
Agent Identity: ${agentName}
Gnosis Safe Address: ${safeAddress}
Listing Price: ${priceXdai} xDAI

TERMS:

1. TRANSFER OF OWNERSHIP
The Seller hereby agrees to transfer to the Buyer full legal and beneficial ownership of:
(a) the AI agent identity "${agentName}" including its on-chain subname registration, 
    associated NFT, and all metadata;
(b) all intellectual property rights subsisting in or associated with "${agentName}" 
    that are owned by or licenced exclusively to the Seller, to the extent transferable;
(c) ownership and control of the Gnosis Safe at ${safeAddress}, including all digital 
    assets held therein at the time of transfer, by transferring the signing threshold 
    and removing the Seller as an owner.

2. BLOCKCHAIN EXECUTION AS LEGAL INSTRUMENT
The parties agree that:
(a) The Seller's EIP-712 cryptographic signature of this Agreement, combined with the 
    on-chain completion of the purchase transaction by the Buyer, constitutes a binding 
    written agreement under the laws of New South Wales, Australia;
(b) Under the Electronic Transactions Act 1999 (Cth) and the Electronic Transactions 
    Act 2000 (NSW), a cryptographic wallet signature satisfies the requirement for a 
    signature in writing;
(c) This Agreement is intended to constitute an effective assignment of intellectual 
    property rights in writing as required by section 197 of the Copyright Act 1968 (Cth)
    to the extent the transferred assets are subject to copyright protection.

3. WARRANTIES BY SELLER
The Seller warrants that:
(a) They are the sole legal and beneficial owner of the agent identity and Gnosis Safe;
(b) The assets are free from encumbrances, liens, and third-party claims;
(c) They have full authority to enter into and perform this Agreement;
(d) No third party has been granted any exclusive licence over the transferred IP.

4. LIMITATIONS
(a) GhostAgent.ninja is not a party to this transfer and provides only the technical 
    infrastructure. GhostAgent.ninja accepts no liability for disputes between Seller 
    and Buyer;
(b) This Agreement does not warrant transfer of IP rights that the Seller does not own,
    including rights in third-party AI models, Story Protocol licence terms, or content 
    generated by AI agents;
(c) The effectiveness of this Agreement as a copyright assignment may vary by jurisdiction.
    Both parties are advised to seek independent legal advice.

5. GOVERNING LAW
This Agreement is governed by the laws of New South Wales, Australia.

6. ENTIRE AGREEMENT
This Agreement, together with the on-chain transaction record, constitutes the entire 
agreement between the parties regarding the transfer of the above-named assets.`;
}

export function MarketplaceTransferAgreement({
  agentName,
  safeAddress,
  listingPriceXdai,
  onSign,
  onCancel,
}: TransferAgreementProps) {
  const [agreed, setAgreed] = useState(false);
  const [signing, setSigning] = useState(false);

  const agreementText = buildAgreementText(agentName, safeAddress, listingPriceXdai);

  async function handleSign() {
    if (!agreed) return;
    setSigning(true);
    try {
      const encoder = new TextEncoder();
      const data = encoder.encode(agreementText);
      const hashBuffer = await crypto.subtle.digest('SHA-256', data);
      const hashArray = Array.from(new Uint8Array(hashBuffer));
      const agreementHash = '0x' + hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
      onSign(agreementHash);
    } catch {
      setSigning(false);
    }
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4 backdrop-blur-sm">
      <div className="flex max-h-[90vh] w-full max-w-2xl flex-col rounded-2xl border border-[var(--border)] bg-[#0f0703] shadow-2xl">
        {/* Header */}
        <div className="border-b border-[var(--border)] px-6 py-4">
          <h2 className="text-base font-semibold text-[#f2eee4]">Marketplace IP Transfer Agreement</h2>
          <p className="mt-0.5 text-[11px] text-[var(--muted)]">
            Read and sign to list <strong className="text-[#b0805c]">{agentName}</strong> · {AGREEMENT_VERSION}
          </p>
        </div>

        {/* Agreement text */}
        <div className="flex-1 overflow-y-auto px-6 py-4">
          <pre className="whitespace-pre-wrap font-mono text-[10px] leading-relaxed text-[#a09080]">
            {agreementText}
          </pre>
        </div>

        {/* Footer */}
        <div className="border-t border-[var(--border)] px-6 py-4 space-y-4">
          <label className="flex cursor-pointer items-start gap-3">
            <input
              type="checkbox"
              checked={agreed}
              onChange={e => setAgreed(e.target.checked)}
              className="mt-0.5 h-4 w-4 shrink-0 cursor-pointer accent-[#b0805c]"
            />
            <span className="text-[11px] leading-relaxed text-[var(--muted)]">
              I have read and agree to this IP Transfer Agreement. I confirm I am the legal owner of{' '}
              <strong className="text-[#f2eee4]">{agentName}</strong> and the Gnosis Safe at{' '}
              <code className="text-[10px] text-[#b0805c]">{safeAddress.slice(0, 6)}…{safeAddress.slice(-4)}</code>.
              I understand my wallet signature constitutes a binding written agreement under Australian law.
            </span>
          </label>

          <div className="flex gap-3">
            <button
              onClick={onCancel}
              className="flex-1 rounded-lg border border-[var(--border)] py-2.5 text-xs text-[var(--muted)] transition hover:border-white/20 hover:text-white"
            >
              Cancel
            </button>
            <button
              onClick={handleSign}
              disabled={!agreed || signing}
              className="flex-1 rounded-lg bg-[#b0805c] py-2.5 text-xs font-semibold text-white transition hover:bg-[#c8935f] disabled:opacity-40 disabled:cursor-not-allowed"
            >
              {signing ? 'Signing…' : 'Sign & List Agent'}
            </button>
          </div>
          <p className="text-center text-[10px] text-[var(--muted)]">
            Agreement hash stored in GlassBox audit trail · governed by NSW, Australia law
          </p>
        </div>
      </div>
    </div>
  );
}
