#!/usr/bin/env node
/**
 * Redeem a tier-upgrade coupon generated by generate-coupon.mjs.
 * Sets KV tier + TLD so the claim route recognises the agent as upgraded.
 *
 * Usage:
 *   WEBHOOK_SECRET=<s> node scripts/redeem-coupon.mjs <coupon>
 *
 * The coupon is the base64url.signature string from generate-coupon.mjs.
 */

import { createHmac, timingSafeEqual } from 'crypto';

const WORKER_URL = process.env.NEXT_PUBLIC_WORKER_URL ?? 'https://nftmail-email-worker.richard-159.workers.dev';
const WORKER_SECRET  = process.env.WORKER_SECRET  ?? '';
const WEBHOOK_SECRET = process.env.WEBHOOK_SECRET ?? '';

if (!WEBHOOK_SECRET) { console.error('WEBHOOK_SECRET required'); process.exit(1); }

const coupon = process.argv[2];
if (!coupon) { console.error('Usage: WEBHOOK_SECRET=<s> node redeem-coupon.mjs <coupon>'); process.exit(1); }

const [payloadB64, sig] = coupon.split('.');
if (!payloadB64 || !sig) { console.error('Invalid coupon format'); process.exit(1); }

// Verify HMAC
const expected = createHmac('sha256', WEBHOOK_SECRET).update(payloadB64).digest('base64url');
if (!timingSafeEqual(Buffer.from(sig), Buffer.from(expected))) {
  console.error('✗ Coupon signature invalid'); process.exit(1);
}

const payload = JSON.parse(Buffer.from(payloadB64, 'base64url').toString());
const { slug, tier, expiry } = payload;

if (expiry > 0 && Date.now() / 1000 > expiry) {
  console.error(`✗ Coupon expired at ${new Date(expiry * 1000).toISOString()}`); process.exit(1);
}

console.log(`\n✓ Coupon valid: ${slug} → ${tier}${expiry ? ` (expires ${new Date(expiry * 1000).toISOString()})` : ' (permanent)'}`);

const headers = {
  'Content-Type': 'application/json',
  'X-Worker-Secret': WORKER_SECRET,
  'X-Webhook-Secret': WEBHOOK_SECRET,
};

// 1. Set tier in KV
const tierRes = await fetch(WORKER_URL, {
  method: 'POST', headers,
  body: JSON.stringify({ action: 'setAgentRecord', agentName: slug, tier, secret: WEBHOOK_SECRET }),
}).then(r => r.json()).catch(() => null);

if (tierRes?.status === 'updated' || tierRes?.ok) {
  console.log(`✓ KV tier set: ${slug} → ${tier}`);
} else {
  console.warn('⚠ KV tier set failed:', JSON.stringify(tierRes));
}

// 2. Set TLD to agent.gno (corroborating signal for isUpgraded check)
const tldRes = await fetch(WORKER_URL, {
  method: 'POST', headers,
  body: JSON.stringify({ action: 'setTld', agentName: slug, tld: 'agent.gno', webhookSecret: WEBHOOK_SECRET }),
}).then(r => r.json()).catch(() => null);

if (tldRes?.status === 'ok' || tldRes?.tld) {
  console.log(`✓ KV tld set: ${slug} → agent.gno`);
} else {
  console.warn('⚠ KV tld set failed:', JSON.stringify(tldRes));
}

console.log(`\nDone. ${slug} is now ${tier}. Have the agent owner re-claim at /normies-lab to refresh their profile.\n`);
